function cfg = defaultRuntimeConfig()
%DEFAULTRUNTIMECONFIG Default runtime options for qwen2_runtime.

    cfg = struct();
    cfg.LinearMode = 'dynamic_int8';
    cfg.WeightScaleMode = 'per_row';
    cfg.ActivationScaleMode = 'per_col';
    cfg.ActivationQuantization = 'affine';
    cfg.UseGroupedActivationQuantization = true;
    cfg.ActivationGroupSize = 128;
    cfg.MlpGateLinearMode = '';
    cfg.MlpUpLinearMode = '';
    cfg.MlpDownLinearMode = '';
    cfg.MlpGateActivationQuantization = '';
    cfg.MlpUpActivationQuantization = '';
    cfg.MlpDownActivationQuantization = '';
    cfg.MlpGateUseGroupedActivationQuantization = false;
    cfg.MlpUpUseGroupedActivationQuantization = false;
    cfg.MlpDownUseGroupedActivationQuantization = false;
    cfg.MlpGateActivationGroupSize = 0;
    cfg.MlpUpActivationGroupSize = 0;
    cfg.MlpDownActivationGroupSize = 0;
    cfg.TailLayerStart = -1;
    cfg.TailMlpGateLinearMode = '';
    cfg.TailMlpUpLinearMode = '';
    cfg.TailMlpDownLinearMode = '';
    cfg.TailMlpGateActivationQuantization = '';
    cfg.TailMlpUpActivationQuantization = '';
    cfg.TailMlpDownActivationQuantization = '';
    cfg.TailMlpGateUseGroupedActivationQuantization = false;
    cfg.TailMlpUpUseGroupedActivationQuantization = false;
    cfg.TailMlpDownUseGroupedActivationQuantization = false;
    cfg.TailMlpGateActivationGroupSize = 0;
    cfg.TailMlpUpActivationGroupSize = 0;
    cfg.TailMlpDownActivationGroupSize = 0;
    cfg.SoftmaxOutlierThreshold = single(32);
    cfg.ResidualFloatThreshold = single(64);
    cfg.ForceFloatLayers = [-1];
    cfg.BlockKernel = 'qwen2_runtime.layer.block';
    cfg.HDLMaxCacheLength = 256;
    cfg.UseExternalWeightMemory = false;
    cfg.UseExternalKVMemory = false;
    cfg.SystemAttentionKernel = '';
    cfg.SystemKVInterfaceKernel = '';
    cfg.SystemAttentionControllerKernel = '';
    cfg.TraceTensors = false;
end
