function args = attention_token_step_sram_args(maxCacheLen, forCodegen)
%ATTENTION_TOKEN_STEP_SRAM_ARGS Representative real-head-dimension args for token-step attention SRAM top.

    if nargin == 0
        maxCacheLen = 8;
    end
    if nargin < 2
        forCodegen = false;
    end

    runtimeCfg = qwen2_runtime.defaultHardwareHDLConfig();
    F = attentionFimath(runtimeCfg);
    headDim = 128;
    numHeads = 12;
    numKVHeads = 2;
    ropeTheta = 1000000.0;

    q_token = fi(reshape(single(linspace(-0.25, 0.25, headDim * numHeads)), [headDim, numHeads]), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);
    k_token = fi(reshape(single(linspace(-0.125, 0.125, headDim * numKVHeads)), [headDim, numKVHeads]), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);
    v_token = fi(reshape(single(linspace(0.125, -0.125, headDim * numKVHeads)), [headDim, numKVHeads]), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);
    key_cache_in = fi(zeros(headDim, numKVHeads, maxCacheLen, 1), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);
    value_cache_in = fi(zeros(headDim, numKVHeads, maxCacheLen, 1), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);
    cache_valid_len = uint16(0);
    rope_position = uint16(1);

    hyperParameters = struct();
    hyperParameters.HiddenSize = headDim * numHeads;
    hyperParameters.NumHeads = numHeads;
    hyperParameters.NumKVHeads = numKVHeads;
    hyperParameters.HeadDim = headDim;
    hyperParameters.RopeTheta = ropeTheta;

    freqsFull = transformer.layer.precomputeFreqsCis(headDim, double(maxCacheLen) + 8, ropeTheta);
    freqs_cis = struct();
    freqs_cis.Cos = fi(single(real(freqsFull(:, 1:double(maxCacheLen) + 8))), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);
    freqs_cis.Sin = fi(single(imag(freqsFull(:, 1:double(maxCacheLen) + 8))), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);

    if forCodegen
        freqsArg = coder.Constant(freqs_cis);
        hyperArg = coder.Constant(hyperParameters);
        cfgArg = coder.Constant(runtimeCfg);
    else
        freqsArg = freqs_cis;
        hyperArg = hyperParameters;
        cfgArg = runtimeCfg;
    end

    args = { ...
        q_token, ...
        k_token, ...
        v_token, ...
        key_cache_in, ...
        value_cache_in, ...
        cache_valid_len, ...
        rope_position, ...
        freqsArg, ...
        hyperArg, ...
        cfgArg};
end

function F = attentionFimath(cfg)
    F = fimath( ...
        'RoundingMethod', 'Floor', ...
        'OverflowAction', 'Saturate', ...
        'ProductMode', 'SpecifyPrecision', ...
        'ProductWordLength', 24, ...
        'ProductFractionLength', cfg.HDLLinearAccumFractionLength, ...
        'SumMode', 'SpecifyPrecision', ...
        'SumWordLength', cfg.HDLLinearAccumWordLength, ...
        'SumFractionLength', cfg.HDLLinearAccumFractionLength);
end