function score = attention_score_step(query_vec, key_vec, scale)
%ATTENTION_SCORE_STEP Small dot-product score kernel.

    F = fimath( ...
        'RoundingMethod', 'Floor', ...
        'OverflowAction', 'Saturate', ...
        'ProductMode', 'SpecifyPrecision', ...
        'ProductWordLength', 24, ...
        'ProductFractionLength', 14, ...
        'SumMode', 'SpecifyPrecision', ...
        'SumWordLength', 32, ...
        'SumFractionLength', 14);

    vecLen = size(query_vec, 1);
    score = fi(0, true, 32, 14, F);
    for i = 1:vecLen
        qVal = fi(query_vec(i), true, 16, 14, F);
        kVal = fi(key_vec(i), true, 16, 14, F);
        score = score + qVal * kVal;
    end
    scaleVal = fi(scale, true, 16, 14, F);
    score = score * scaleVal;
end
