function args = block_entry_hardware_args()
%BLOCK_ENTRY_HARDWARE_ARGS Representative reduced-dimension args for fixed-point block HDL baseline.

    hiddenSize = 8;
    seqLen = 1;
    batchSize = 1;
    numHeads = 2;
    numKVHeads = 2;
    headDim = 4;
    mlpSize = 16;
    maxCacheLen = 4;

    runtimeCfg = qwen2_runtime.defaultHardwareHDLConfig();
    F = blockFimath(runtimeCfg);

    h_in = fi(reshape(single(linspace(-0.25, 0.25, hiddenSize)), hiddenSize, seqLen, batchSize), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);
    key_in = fi(zeros(headDim, numKVHeads, maxCacheLen, batchSize), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);
    value_in = fi(zeros(headDim, numKVHeads, maxCacheLen, batchSize), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);
    cache_valid_len = 0;

    weights = struct();
    weights.input_layernorm = fi(reshape(single(linspace(0.95, 1.05, hiddenSize)), hiddenSize, 1), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);
    weights.post_attention_layernorm = fi(reshape(single(linspace(1.05, 0.95, hiddenSize)), hiddenSize, 1), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);
    weights.self_attn_q_proj = fi(makeMatrix(hiddenSize, hiddenSize, 0.125, 0.0), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);
    weights.self_attn_k_proj = fi(makeMatrix(hiddenSize, hiddenSize, 0.125, 0.7), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);
    weights.self_attn_v_proj = fi(makeMatrix(hiddenSize, hiddenSize, 0.125, 1.3), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);
    weights.self_attn_o_proj = fi(makeMatrix(hiddenSize, hiddenSize, 0.125, 2.1), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);
    weights.mlp_gate_proj = fi(makeMatrix(mlpSize, hiddenSize, 0.075, 0.4), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);
    weights.mlp_up_proj = fi(makeMatrix(mlpSize, hiddenSize, 0.075, 1.1), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);
    weights.mlp_down_proj = fi(makeMatrix(hiddenSize, mlpSize, 0.075, 1.8), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);

    hyperParameters = struct();
    hyperParameters.HiddenSize = hiddenSize;
    hyperParameters.NumHeads = numHeads;
    hyperParameters.NumKVHeads = numKVHeads;
    hyperParameters.HeadDim = headDim;
    hyperParameters.RopeTheta = 10000.0;

    freqsFull = transformer.layer.precomputeFreqsCis(headDim, seqLen + 8, hyperParameters.RopeTheta);
    freqs_cis = struct();
    freqs_cis.Cos = fi(single(real(freqsFull(:, 1:seqLen))), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);
    freqs_cis.Sin = fi(single(imag(freqsFull(:, 1:seqLen))), ...
        true, runtimeCfg.HDLLinearInputWordLength, runtimeCfg.HDLLinearInputFractionLength, F);

    args = { ...
        h_in, ...
        key_in, ...
        value_in, ...
        coder.Constant(cache_valid_len), ...
        coder.Constant(weights), ...
        coder.Constant(hyperParameters), ...
        coder.Constant(freqs_cis), ...
        coder.Constant(runtimeCfg)};
end

function W = makeMatrix(rows, cols, scale, phase)
    values = sin(single(1:(rows * cols)) + single(phase));
    W = reshape(single(scale) .* single(values), rows, cols);
end

function F = blockFimath(cfg)
    F = fimath( ...
        'RoundingMethod', 'Floor', ...
        'OverflowAction', 'Saturate', ...
        'ProductMode', 'SpecifyPrecision', ...
        'ProductWordLength', 24, ...
        'ProductFractionLength', cfg.HDLLinearAccumFractionLength, ...
        'SumMode', 'SpecifyPrecision', ...
        'SumWordLength', cfg.HDLLinearAccumWordLength, ...
        'SumFractionLength', cfg.HDLLinearAccumFractionLength);
end