function info = check_small_kernels_codegen()
%CHECK_SMALL_KERNELS_CODEGEN Run HDL codegen on smaller kernels.

    projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    kernels = { ...
        struct('name', 'qwen2_runtime_hdl_linear_tile_fixpt_entry', 'argsExpr', 'qwen2_runtime.hdl.linear_tile_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_linear_tile_serial_entry', 'argsExpr', 'qwen2_runtime.hdl.linear_tile_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_linear_tile_pair4_entry', 'argsExpr', 'qwen2_runtime.hdl.linear_tile_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_linear_row_mac_entry', 'argsExpr', 'qwen2_runtime.hdl.linear_row_mac_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_linear_row_controller_entry', 'argsExpr', 'qwen2_runtime.hdl.linear_row_controller_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_linear_tile_controller_entry', 'argsExpr', 'qwen2_runtime.hdl.linear_tile_controller_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_kv_cache_entry', 'argsExpr', 'qwen2_runtime.hdl.kv_cache_update_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_kv_cache_lane_entry', 'argsExpr', 'qwen2_runtime.hdl.kv_cache_lane_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_attention_score_entry', 'argsExpr', 'qwen2_runtime.hdl.attention_score_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_attention_score_mac_entry', 'argsExpr', 'qwen2_runtime.hdl.attention_score_mac_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_attention_row_controller_entry', 'argsExpr', 'qwen2_runtime.hdl.attention_row_controller_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_attention_value_mac_entry', 'argsExpr', 'qwen2_runtime.hdl.attention_value_mac_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_attention_value_row_controller_entry', 'argsExpr', 'qwen2_runtime.hdl.attention_value_row_controller_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_softmax_max_entry', 'argsExpr', 'qwen2_runtime.hdl.softmax_max_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_softmax_exp_entry', 'argsExpr', 'qwen2_runtime.hdl.softmax_exp_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_softmax_sum_entry', 'argsExpr', 'qwen2_runtime.hdl.softmax_sum_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_softmax_recip_lookup_entry', 'argsExpr', 'qwen2_runtime.hdl.softmax_recip_lookup_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_softmax_normalize_entry', 'argsExpr', 'qwen2_runtime.hdl.softmax_normalize_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_residual_add_entry', 'argsExpr', 'qwen2_runtime.hdl.residual_add_step_args()'), ...
        struct('name', 'qwen2_runtime_hdl_block_fullattn_baseline_entry', 'argsExpr', 'qwen2_runtime.hdl.block_fullattn_baseline_step_args()')};

    info = struct('Kernel', {}, 'OutputDir', {}, 'Succeeded', {});
    for i = 1:numel(kernels)
        outDir = fullfile(projectRoot, 'codegen', 'hdl_small', kernels{i}.name);
        if ~exist(outDir, 'dir')
            mkdir(outDir);
        end
        runKernelCodegen(kernels{i}.name, kernels{i}.argsExpr, outDir, projectRoot);
        info(i).Kernel = kernels{i}.name;
        info(i).OutputDir = outDir;
        info(i).Succeeded = true;
    end
end

function runKernelCodegen(kernelName, argsExpr, outDir, projectRoot)
    cfg = coder.config('hdl');
    cfg.TargetLanguage = 'Verilog';
    cfg.GenerateHDLTestBench = false;
    cfg.GenerateCosimTestBench = false;
    cfg.SynthesizeGeneratedCode = false;
    cfg.Workflow = 'Generic ASIC/FPGA';
    cfg.FloatingPointLibrary = 'NativeFloatingPoint';
    cfg.FloatingPointTargetConfiguration = hdlcoder.createFloatingPointTargetConfig('NativeFloatingPoint');
    cfg.InstantiateFunctions = true;

    eval(sprintf('args = %s;', argsExpr));
    codegen('-config', cfg, kernelName, '-args', args, '-d', outDir, '-I', projectRoot);
end
