function weight_out = softmax_normalize_step(exp_val, denom_recip)
%SOFTMAX_NORMALIZE_STEP Multiply exp approximation by reciprocal denominator.

    coder.inline('never');

    F = normFimath();
    exp_fix = fi(exp_val, true, 16, 14, F);
    recip_fix = fi(denom_recip, true, 16, 14, F);
    product = fi(exp_fix * recip_fix, true, 16, 14, F);
    weight_out = product;
end

function F = normFimath()
    F = fimath( ...
        'RoundingMethod', 'Floor', ...
        'OverflowAction', 'Saturate', ...
        'ProductMode', 'SpecifyPrecision', ...
        'ProductWordLength', 24, ...
        'ProductFractionLength', 14, ...
        'SumMode', 'SpecifyPrecision', ...
        'SumWordLength', 16, ...
        'SumFractionLength', 14);
end
